language: go
go:
- tip
addons:
  apt:
    packages:
    - ruby-dev
    - gcc
    - make
    - rpm
before_install:
- gem install fpm
- go get github.com/mitchellh/gox
deploy:
  provider: releases
  api_key:
    secure: ChmFOui9J29d4xnams+9ZzwUXCnCrZJTCK42rJmYttVDuYJV5AHNpOzE1w0KkDdlABOGtm8MH9ItVI2rnY35R0oTryNA/b/9NCIAeU/PecLwVMbLzQgeOe/cmO0D3pG6aUf6cXnP9YZp9sNaqzOMFOXJRSBZKHL1HxUWygaRDN7fKgwyGcjcQm88cdaa+dqQ9hre0R0vT3g2fLsC69cP8pwIUW09hSfGjHsvJdzBTw8Ak2WBvHJ7dW+aAM6vNofetm2cKQ4xqZqX6la08xYt36B7E+TY3HsKZCyPUVfyJIo1dVj1QzaeX1OW0EPI5hOPF40qP1TEv9fHGh/s9lk4PDgsj2f2vB0Eid8OrfiC7rg94fc6JwUvACc9/icJ4GR3/V/ea6m/qy4NmwNGMW7089sMMwF9kJzJy1+YgxP6so07vpXHFS0EZ4FSs1vIBRykYfX30v0ajmupysXauUILXiUS0c+QRXlWC5w+2Q4witWoLWcAySGNd+hctvGBm5o425Ax5/EyDmt4hcJd+TcANn9MUQKqBZCMLhOZNtHLs56N9xI/t8MVruhXPx3mJUuBShno2Tpal2vzxJWa0YCeCjsAzk66xjyjA0WL2qGthYwytdPAteKxdkY1u1wE7WsxGv22+x++cOLnrxyqo/M/+DbtbODYT8rNOmxIgJHX5cI=
  file_glob: true
  file: packages/*
  skip_cleanup: true
  on:
    tags: true
