language: go
go:
- 1.6
addons:
  apt:
    packages:
    - ruby-dev
    - gcc
    - make
before_install:
- gem install fpm
after_success:
- go build
- mkdir -p package/deb/usr/sbin
- cp -v udpac package/deb/usr/sbin
- "./package/fpm.sh"
deploy:
  provider: releases
  api_key:
    secure: W3p/l8BaZsTwSZ2yz/kn8EQ/2PT4zEiBHSGcK2mqe6srSsvbvJANNqP3Vsw6HAoq1E2wnVL8r6eo/qvh3zsnzsSxtCfB9SHM/mhwInDEGpbsjspxplBWrZxmWjhBGDbszmouBLZ68hMV1Ru7CCIigma4zpqtsk7g6SPypVoNHTYNAihwwWRFb0X1yOBkkWXxHnkf5Zn27pxFgsx9tiedwciX01SvEywPrb1d6TPswqm9BEyMGnt5oHgFUo5tAhPE5sU+IqrfcnhJopCYvmb8Na+BTSGxiuXNJ2SBJ7bKomXMAHhA20lVkFkL+JM3tKYACQGcoAZ5BSsunHhUMtcpoTOblwOijO1kg/8QgsGjttKZUA7DeUObmVhmj8jXS6bEwhEtxbkw6voEfod58X6R3PLBviPBQYO/p6dAxcISaOP2g7oL73j9AWFayxXsqsETfH83fx5iJpBNuNGoDPY19PBdamNtj9Pr1iUc24oRQ0tHLWDAR+GGhLheN7INSarWHX8Ql4I7WMmsLRF/L7fQbpQMraTwvBYfdxwpdM2Ymu9ME6w5kHswch0CApv02fqGvUhmki9akxac6bIagbfamwmz/F3RXlADtvFN9uYNnhgFCjUsP3/csPJmRaJiDQqYSaYUFC5vM1ykMQSNJoI/44bfiGo7k6k0AlrG6a9LEZ0=
  file_glob: true
  file:
  - "*.deb"
  skip_cleanup: true
  on:
    tags: true
