language: go
go:
- 1.6
addons:
  apt:
    packages:
    - ruby-dev
    - gcc
    - make
    - rpm
before_install:
- gem install fpm
deploy:
  provider: releases
  api_key:
    secure: E+JAEhScBnaPFYUiS8lCEvPtfJZTOcu30e+UDEHP6I9N48w3dzya3KHkb6tjiQiMWRaW8tGOkVE6P35KjkcQN1VL0rSKULYYCq52LysUaf2mzaUTpJqxxvxCsgOMFZTa/kqQdAJ+XhihS2xfbsk8CEMA1UdtdMe2N3Zo8A+NYoi0ZgKfmRJ4f8LcQM8dqfaij8Kg7NBjxxQK2GoH/eMCLHK/IJhhnJqth+4j3vjQ2IiBbswu+8YHDFYIkMYQSz14tx8wOmTa/Knk5JkpJJL+cOZNBMb4w1yn5VM2Zgq+phGj0NS/yhsSfO5xem9l8TFUozZ0o9K0zZgMo+kIJdys8Siyhg2R3yRFzKX7sZGHV2e1fzud6YdP6G2HdhY+4xdLH38XEkqZQWInjXX0Ms6nNU2lvrCBqj5uCe9VsS4ay1aedV5XiO5tfXwyOrZMQGEjCA7HyWzU6A80JbevLCHXDvarRe4Q0+BrsHTXqNmxO2xGBQhsOwdftOeIy9i/LY1ZcHmKRVFdaKY0PFW2iXYpOcbcWzQD8tGX3k7G/FdAsKYR594RPj7N2aUoafOpUXenWx532XUrLXFJEjH1FRC317aK/PLIAuY/zj+rXlEn4Q4kQARyB/MgteepS/hjWWVVQ2mi2pX5zUnMLa4ZyzszXMhtkhwwVnxfN0qsWtPcjX8=
  file_glob: true
  file: packages/*
  skip_cleanup: true
  on:
    tags: true
